### PR TITLE
add secret types cases

### PR DESCRIPTION
**Pull request by ropatil010**
Hi Team, 

Kindly PTAL when ever get a chance. 
Adding two cases which i have executed here: https://issues.redhat.com/browse/STOR-1691 
secret types: basicauth, dockerconfigjson.

### CODE REVIEW

**Comment by ropatil010** [comment]
cc: @dobsonj @jsafrane ++

**Comment by ropatil010** [comment]
rohitpatil@ropatil-mac secrets-store-csi-driver % make e2e-vault
bats -t test/bats/vault.bats
1..25
ok 1 install vault provider
ok 2 setup vault
ok 3 deploy vault secretproviderclass crd
ok 4 CSI inline volume test with pod portability
ok 5 CSI inline volume test with pod portability - read vault secret from pod
ok 6 CSI inline volume test with pod portability - rotation succeeds
ok 7 CSI inline volume test with pod portability - unmount succeeds
ok 8 Sync,rotate with basicauth K8s secrets - create deployment
ok 9 Sync with basicauth K8s secrets - read vault secret from pod and basicauth secret
ok 10 Rotate with basicauth K8s secrets - read vault secret from pod and basicauth secret
ok 11 Sync,rotate with basicauth K8s secrets - unmount succeeds, secret gets deleted
ok 12 Sync,rotate with dockerconfigjson K8s secrets - create deployment
ok 13 Sync with dockerconfigjson K8s secrets - read vault secret from pod and dockerconfigjson secret
ok 14 Rotate with dockerconfigjson K8s secrets - read vault secret from pod and dockerconfigjson secret
ok 15 Sync,rotate with dockerconfigjson K8s secrets - unmount succeeds, secret gets deleted
ok 16 Sync with K8s secrets - create deployment
ok 17 Sync with K8s secrets - read secret from pod, read K8s secret, read env var, check secret ownerReferences with multiple owners
ok 18 Sync with K8s secrets - delete deployment, check secret is deleted
ok 19 Test Namespaced scope SecretProviderClass - create deployment
ok 20 Test Namespaced scope SecretProviderClass - Sync with K8s secrets - read secret from pod, read K8s secret, read env var, check secret ownerReferences
ok 21 Test Namespaced scope SecretProviderClass - Sync with K8s secrets - delete deployment, check secret deleted
ok 22 Test Namespaced scope SecretProviderClass - Should fail when no secret provider class in same namespace
ok 23 deploy multiple vault secretproviderclass crd
ok 24 deploy pod with multiple secret provider class
ok 25 CSI inline volume test with multiple secret provider class

**Comment by jsafrane** [comment]
IMO all the new tests belong to upstream, not our OpenShift fork.

**Comment by ropatil010** [comment]
Ack, Thanks for inputs @jsafrane. Will try to add in upstream repo.

Need 1 more input. 
In file pod-vault-inline-volume-secretproviderclass-dockerconfigjson-sync-rotate.yaml i have added image as quay.io/openshifttest/hello-openshift@sha256:b1aabe8c8272f750ce757b6c4263a2712796297511e0c6df79144ee188933623
Since i need to trigger command jq -r inside pod 
Command: kubectl exec secrets-store-inline-dockerconfigjson-sync-rotate -- cat /mnt/secrets-store/dockerconfigjson | jq -r '.auths["https://index.docker.io/v1/"].username'
If i use there image registry.k8s.io/e2e-test-images/busybox:1.29-4 it wont work, as there is no jq command. 
Which image can i use?

**Comment by dobsonj** [comment]
@ropatil010 could you compare the entire json string in the test instead of using `jq` in the container? The busybox image is tiny and widely used in e2e tests, it would be simpler to stick with that image.

Something like this might work? Then you wouldn't have to compare username and password separately.

```
expected="{\"auths\": {\"https://index.docker.io/v1/\": {\"username\": \"tiger-rotated\",\"password\": \"pass1234-rotated\",\"email\": \"dummy-user-rotated@redhat.com\",\"auth\": \"dGlnZXI6cGFzczEyMzQ=\"}}}"

kubectl exec vault-0 --namespace=vault -- vault kv put secret/db-dockerconfigjson .dockerconfigjson=$expected

value=$(oc get secrets/dockerconfigjsonsecret -o=jsonpath="{.data.\.dockerconfigjson}" | base64 -d)
[[ "$value" == "$expected" ]]
```

**Comment by ropatil010** [comment]
Thanks @dobsonj for inputs. Will try with your suggestions.

**Pull request closed without merging**
